language: bash
dist: trusty
sudo: required

branches:
  only:
    - master

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DOCKER_DESCRIPTION="ubuntu base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="ubuntu"
    - DOCKER_URL="https://www.ubuntu.com/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="`git rev-parse --short HEAD`"
    - VCS_URL="`git remote get-url origin | head -c-5`"

  matrix:
    - DOCKER_TAG="latest"
      DOCKER_VERSION="bionic"
      DOWNLOAD_URL="http://cdimage.ubuntu.com/ubuntu-base/daily/current/`curl -s http://cdimage.ubuntu.com/ubuntu-base/daily/current/ | grep 'amd64.tar.gz' | awk -F '>' {'print $7'} | head -n 1 | awk -F '<' {'print $1'}`"
    - DOCKER_TAG="stable"
      DOCKER_VERSION="artful"
      DOWNLOAD_URL="http://cdimage.ubuntu.com/ubuntu-base/releases/${DOCKER_VERSION}/release/`curl -s http://cdimage.ubuntu.com/ubuntu-base/releases/${DOCKER_VERSION}/release/ | grep amd64 | awk -F '>' {'print $7'} | head -n 1 | awk -F '<' {'print $1'}`"
      
before_install:
  - sudo apt-get update -q
  - sudo apt-get upgrade -q -y
  - docker version

install:
#  - docker build
#  - docker run bash "exit"
#  - docker export | docker import --change "CMD /bin/bash" --message "this is a message" ubuntu:$DOCKER_VERSION
  - docker import ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

#before_script:
#  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile

#script:
#  - >
#    docker build
#    --label org.label-schema.build-date="$BUILD_DATE"
#    --label org.label-schema.build-number="$BUILD_NUMBER"
#    --label org.label-schema.description="$DOCKER_DESCRIPTION"
#    --label org.label-schema.maintainer="$DOCKER_MAINTAINER"
#    --label org.label-schema.name="$DOCKER_NAME"
#    --label org.label-schema.url="$DOCKER_URL"
#    --label org.label-schema.version="$DOCKER_VERSION"
#    --label org.label-schema.schema-version="$SCHEMA_VERSION"
#    --label org.label-schema.vcs-ref="$VCS_REF"
#    --label org.label-schema.vcs-url="$VCS_URL"
#    --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}
#    --pull .

#after_success:
#  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
#  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
